export const REQUEST_TICKETS = 'REQUEST_TICKETS'
export const SET_PRICES = 'SET_PRICES'
export const SET_DATE = 'SET_DATE'
export const REQUEST_DATE = 'REQUEST_DATE'
export const LIKE = 'LIKE'
export const DISLIKE = 'DISLIKE'
export const IS_LIKED = 'IS_LIKED'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGIN_FINISH = 'LOGIN_FINISH'
export const LOGOUT_FINISH = 'LOGOUT_FINISH'
export const INIT_USERDATA = 'INIT_USERDATA'

